fail_fast: false

repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: make lint
        types: [python]
        language: system
        pass_filenames: false

      - id: mypy
        name: type check
        entry: make ty
        types: [python]
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.5
    hooks:
      - id: uv-lock
        name: Lockfile

