services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - qdrant
    environment:
      - LOG_CFG=/backend/logs/logging.yml
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    env_file:
      - .env

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HOST=0.0.0.0

volumes:
  qdrant_data:
