services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - chroma
    environment:
      - LOG_CFG=/backend/logs/logging.yml
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    env_file:
      - .env

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index # persistent
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_GRPC_PORT=50051

volumes:
  chroma_data: